# Generated by Django 5.0.7 on 2024-08-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_employee_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='badge_number',
            new_name='registry',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='ra',
            new_name='registry',
        ),
    ]
